### ISSUE TITLE
TypeError: this.indent is not a function

### ISSUE THREAD

**Issue by louisskelton** [shunkosa/sfdx-cmdt-plugin#11]
Hello again! I hope you're well.

I'm having another issue here. I've installed this on another machine and I'm getting the error:

`TypeError: this.indent is not a function`

I'm on Mac - here's the sfdx --version info:  `sfdx-cli/7.63.0-c897e8bb1a darwin-x64 node-v10.20.1`

I'm on version `0.0.7` of the plugin.

[Here's a link to the csv](https://www.dropbox.com/s/d97andgxqlnn0qq/test2.csv?dl=0)

Thank you! This plugin has been so useful :)

Here's the full error:

```
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
TypeError: this.indent is not a function
    at XMLStreamWriter.module.exports.XMLWriterBase.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:136:16)
    at XMLStreamWriter.module.exports.XMLStreamWriter.declaration (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:59:70)
    at XMLStreamWriter.module.exports.XMLWriterBase.writeChildNode (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLWriterBase.js:270:23)
    at XMLStreamWriter.module.exports.XMLStreamWriter.document (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLStreamWriter.js:41:27)
    at XMLDocument.module.exports.XMLDocument.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLDocument.js:143:21)
    at XMLElement.module.exports.XMLNode.end (/Users/louis/.local/share/sfdx/node_modules/xmlbuilder/lib/XMLNode.js:486:30)
    at Convert.generateMetadataRecord (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:136:13)
    at Parser.csvstream.pipe.on (/Users/louis/.local/share/sfdx/node_modules/sfdx-cmdt-plugin/lib/commands/cmdt/csv/convert.js:100:22)
    at Parser.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
```

**Comment by louisskelton** [comment]
Not sure if it's useful - but when I install the plugin I get `warning "@oclif/plugin-autocomplete > @oclif/command@1.5.19" has unmet peer dependency "@oclif/plugin-help@^2"`

**Comment by shunkosa** [comment]
Thanks for reporting. I cannot repro it with my sample csv files. Still in the investigation.

**Comment by louisskelton** [comment]
Thank you so much 🙏 !

I literally just tried again with a much simler Custom Metadata Type and CSV and get the same error. Here's the CSV I used:

```
DeveloperName,Label,Test_Field__c
test,test,test
```
Unfortunately the reason I'm on another computer is because my main one has failed! I do have another laptop kicking around. I'll see if I have any different luck there.

**Comment by louisskelton** [comment]
Hello! I've tried spinning this up on another computer (again, a MacBook), and I'm getting exactly the same error: `TypeError: this.indent is not a function`.

Let me know if I can provide any other useful info!

**Comment by louisskelton** [comment]
Hello! I can see the issue:

If you roll-back this change (which seemed to fix my last problem... 😬) it fixes the error I was seeing:

https://github.com/shunkosa/sfdx-cmdt-plugin/commit/d8246743aa82376fb9f666371292e215c0fb355b

So perhaps my other computer had a bad dependency or something? I don't know. Thanks again for making such an amazing plugin!!!! 👍 ❤️

**Comment by shunkosa** [comment]
@louisskelton Thank you for your help. It's exactly the reason, and I had the same issue in another laptop with clean installation. I confirmed the dependency and rollbacked the writer option. Could you please try v0.0.8? Sorry for the inconvenience!

**Comment by louisskelton** [comment]
Thats sorted it - thank you so much! I'll close the issue 👌
